### PR TITLE
Added My Name  Jobayer Mannan

### PR DESCRIPTION
**Pull request by jobayermannan**

### CODE REVIEW

**Comment by klorine28** [comment]
Hello, we are very excited to have your contribution. Unfortunately, there is a minor merge conflict with overlapping code. Please fix the conflict so that it may be merged. If you have any issues, I'll Be happy to help.

**Comment by klorine28** [comment]
Yes, no problem. I am glad to help you. See it before the comment window or after it. There should be a grey branch symbol that says, "This branch has conflicts". If you click on "Resolve conflicts.", you can see what section of the code is conflicting, as seen below.

image

The issue is that this section needs to include all the closing formatting components. They are opened but not closed, creating a merge conflict.


image_2023-08-23_164719142


To fix it, you only need to add the closing format bits of code. I hope you learn a bit more from this. Communication with maintainers and conflict resolution is a big part and a scary one of GitHub's contributions.

If you have any questions or need any help, I'm happy to lend a hand.

**Comment by klorine28** [comment]
Great job next time just remember proper indentation.

**Comment by jobayermannan** [comment]
“Bro,
 it’s not working. There is still some issue. Anyway, thanks for your help. I am glad that you helped me.

**Comment by klorine28** [comment]
It allowed me to merge with no conflicts and if you see this page "https://github.com/quine-sh/Your-First-Contribution/blob/main/QuineContributors.md" it works.

**Pull request merged**
